services:
    rocloud.commands.create_user:
        class: RoCloud\UserBundle\Command\CreateIngameAccountCommand
        arguments:
            - ~
            - '@doctrine.orm.entity_manager'
            - '@rocloud.account_manager'
            - '@fos_user.user_manager.default'
        tags:
            - { name: 'console.command', command: 'ro:create-user'}
