imports:
    - { resource: 'commands.yml' }

services:
    rocloud.md5_encoder:
        class: RoCloud\UserBundle\Encoder\Md5PasswordEncoder

    rocloud.account_manager:
        class: RoCloud\UserBundle\Entity\Manager\AccountManager
        arguments:
            - '@rocloud.md5_encoder'
            - "@=service('doctrine.orm.entity_manager').getRepository('RoCloudUserBundle:IngameAccount')"

    RoCloud\UserBundle\Entity\Manager\AccountManagerInterface: '@rocloud.account_manager'
